services:
  backend-service:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
    - 9000:9000
    depends_on:
      - redis-service
    environment:
      - REDIS_DNS=redis-service

  frontend-service:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - backend-service
    environment:
      - BACKEND_DNS=backend-service
      - BACKEND_PORT=9000
  
  redis-service:
    container_name: redis
    image: docker.io/library/redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/root/redis

volumes:
  redis-data:
