services:
  backend-service:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
    - 9000:9000
  
  frontend-service:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - backend-service
    environment:
      - BACKEND_DNS=backend-service
      - BACKEND_PORT=9000
