services:
  backend-service:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
  
  frontend-service:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - backend-service
