apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      run: backend
  template:
    metadata:
      labels:
        run: backend
    spec:
      initContainers:
        - name: wait-for-redis
          image: busybox
          command: ['sh', '-c', sleep 10]
      containers:
      - name: backend
        image: ghcr.io/lilpernil/go-app:latest
        env:
          - name: REDIS_DNS
            value: redis
