apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      run: frontend
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/lilpernil/go-app-ui:latest
        env:
          - name: BACKEND_DNS
            value: backend-svc
          - name: BACKEND_PORT
            value: '9000'
