apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ .Values.frontend.label }}
  name: {{ .Values.frontend.service.name }}
spec:
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
  selector:
    run: {{ .Values.frontend.label }}
  type: NodePort