apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ .Values.redis.label }}
  name: {{ .Values.redis.service.name }}
spec:
  ports:
  - port: {{ .Values.redis.service.port }}
    protocol: TCP
    targetPort: {{ .Values.redis.service.targetPort }}
  selector:
    run: {{ .Values.redis.label }}
  type: ClusterIP