apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.redis.pvcName }}
spec:
  storageClassName: {{ .Values.redis.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.storage }}