name: Release Workflow
on:
  push:
    branches:
      - main
env:
  docker_username: ${{ github.actor }} 
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  registry_name: lilpernil
  GIT_COMMIT: ${{ github.sha }}
jobs: 

  Build: 
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Build
        run: bash ci/build-app.sh
      - name: Upload Repo
        uses: actions/upload-artifact@v4
        with:
          name: go-app
          path: .

  Publish-Docker:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
      - name: Download Repo
        uses: actions/download-artifact@v4
        with:
          name: go-app
          path: .
      - name: ls
        run: ls -la ci
      - name: Build Docker - Frontend
        run: bash ci/build-docker-frontend.sh
      - name: Build Docker - Backend
        run: bash ci/build-docker-backend.sh
      - name: Push Docker - Frontend
        run: bash ci/push-docker-frontend.sh
      - name: Push Docker - Backend
        run: bash ci/push-docker-backend.sh
  
  Deploy-Production:
    runs-on: ubuntu-latest
    needs: [Publish-Docker]
    permissions:
      packages: read
    steps:
      - name: Get Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
      - name: Deploy Frontend
        run: kubectl --kubeconfig kubeconfig set image deployment frontend frontend=ghcr.io/${{ env.registry_name }}/go-app-ui:${{ env.GIT_COMMIT}}
      - name: Deploy Backend
        run: kubectl --kubeconfig kubeconfig set image deployment backend backend=ghcr.io/${{ env.registry_name }}/go-app:${{ env.GIT_COMMIT}}
      


