name: ValidatePR

on:
  pull_request:
    branches:
      - main

env:
  registry_name: lilpernil 
  GIT_COMMIT: ${{ github.sha }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Build Application
        run: bash ci/build-app.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: go-app
          path: .

  Build-Docker-Scan-Trivy:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: go-app
          path: .

      - name: Build Docker Images
        run: |
          bash ci/build-docker-frontend.sh
          bash ci/build-docker-backend.sh

      - name: Run Trivy - Frontend
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'ghcr.io/lilpernil/go-app-ui'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy - Backend
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'ghcr.io/lilpernil/go-app'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  Test:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: go-app
          path: .

      - name: Run Tests
        run: bash ci/frontend-unittest.sh
