name: ValidatePR
on:
  pull_request:
    branches:
      - main
jobs:
  Build: 
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Build
        run: bash ci/build-app.sh
      - name: Upload Repo
        uses: actions/upload-artifact@v4
        with:
          name: go-app
          path: .
  Test:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
    - name: download Repo
      uses: actions/download-artifact@v4
      with:
        name: go-app
        path: .
    - name: Run Test
      run: bash ci/frontend-unittest.sh
